<?php

namespace Database\Seeders;

use App\Models\ExtendedServiceCategory;
use Illuminate\Database\Seeder;

class ExtendedServiceCategorySeeder extends Seeder
{
    public function run()
    {
        $categories = [
            // СЕКС УСЛУГИ
            [
                'name' => 'Секс классический',
                'type' => 'sex',
                'description' => 'Традиционный вагинальный секс',
                'sort_order' => 1,
                'is_adult_only' => true,
                'min_age' => 18,
                'base_additional_cost' => 0,
                'icon' => 'heart',
                'color' => 'red',
            ],
            [
                'name' => 'Секс анальный',
                'type' => 'sex',
                'description' => 'Анальный секс',
                'sort_order' => 2,
                'is_adult_only' => true,
                'min_age' => 18,
                'base_additional_cost' => 5000,
                'icon' => 'heart',
                'color' => 'red',
            ],
            [
                'name' => 'Секс групповой',
                'type' => 'sex',
                'description' => 'Секс с несколькими партнерами',
                'sort_order' => 3,
                'is_adult_only' => true,
                'min_age' => 21,
                'base_additional_cost' => 5000,
                'icon' => 'users',
                'color' => 'red',
            ],
            [
                'name' => 'Услуги семейной паре',
                'type' => 'sex',
                'description' => 'Услуги для семейной пары',
                'sort_order' => 4,
                'is_adult_only' => true,
                'min_age' => 21,
                'base_additional_cost' => 5000,
                'icon' => 'users',
                'color' => 'red',
            ],
            [
                'name' => 'Минет без презерватива',
                'type' => 'sex',
                'description' => 'Оральный секс без защиты',
                'sort_order' => 5,
                'is_adult_only' => true,
                'min_age' => 18,
                'base_additional_cost' => 3000,
                'default_restrictions' => ['medical_certificate_required'],
                'icon' => 'warning',
                'color' => 'orange',
            ],
            [
                'name' => 'Минет глубокий',
                'type' => 'sex',
                'description' => 'Глубокий оральный секс',
                'sort_order' => 6,
                'is_adult_only' => true,
                'min_age' => 18,
                'base_additional_cost' => 0,
                'icon' => 'heart',
                'color' => 'red',
            ],
            [
                'name' => 'Кунилингус',
                'type' => 'sex',
                'description' => 'Оральная стимуляция женщины',
                'sort_order' => 7,
                'is_adult_only' => true,
                'min_age' => 18,
                'base_additional_cost' => 0,
                'icon' => 'heart',
                'color' => 'red',
            ],
            [
                'name' => 'Игрушки',
                'type' => 'sex',
                'description' => 'Использование секс-игрушек',
                'sort_order' => 8,
                'is_adult_only' => true,
                'min_age' => 18,
                'base_additional_cost' => 0,
                'icon' => 'star',
                'color' => 'purple',
            ],
            [
                'name' => 'Окончание на грудь',
                'type' => 'sex',
                'description' => 'Эякуляция на грудь',
                'sort_order' => 9,
                'is_adult_only' => true,
                'min_age' => 18,
                'base_additional_cost' => 0,
                'icon' => 'heart',
                'color' => 'red',
            ],
            [
                'name' => 'Окончание на лицо',
                'type' => 'sex',
                'description' => 'Эякуляция на лицо',
                'sort_order' => 10,
                'is_adult_only' => true,
                'min_age' => 18,
                'base_additional_cost' => 0,
                'icon' => 'heart',
                'color' => 'red',
            ],
            [
                'name' => 'Окончание в рот',
                'type' => 'sex',
                'description' => 'Эякуляция в рот',
                'sort_order' => 11,
                'is_adult_only' => true,
                'min_age' => 18,
                'base_additional_cost' => 0,
                'icon' => 'heart',
                'color' => 'red',
            ],

            // BDSM УСЛУГИ
            [
                'name' => 'Фетиш',
                'type' => 'bdsm',
                'description' => 'Фетишистские практики',
                'sort_order' => 1,
                'is_adult_only' => true,
                'min_age' => 21,
                'base_additional_cost' => 0,
                'icon' => 'lightning',
                'color' => 'black',
            ],
            [
                'name' => 'Трамплинг',
                'type' => 'bdsm',
                'description' => 'Хождение по телу',
                'sort_order' => 2,
                'is_adult_only' => true,
                'min_age' => 21,
                'base_additional_cost' => 0,
                'icon' => 'lightning',
                'color' => 'black',
            ],
            [
                'name' => 'Ролевые игры',
                'type' => 'bdsm',
                'description' => 'Различные ролевые сценарии',
                'sort_order' => 3,
                'is_adult_only' => true,
                'min_age' => 18,
                'base_additional_cost' => 0,
                'icon' => 'mask',
                'color' => 'purple',
            ],
            [
                'name' => 'Страпон',
                'type' => 'bdsm',
                'description' => 'Использование страпона',
                'sort_order' => 4,
                'is_adult_only' => true,
                'min_age' => 21,
                'base_additional_cost' => 5000,
                'icon' => 'lightning',
                'color' => 'black',
            ],
            [
                'name' => 'Фистинг анальный вам',
                'type' => 'bdsm',
                'description' => 'Анальный фистинг клиенту',
                'sort_order' => 5,
                'is_adult_only' => true,
                'min_age' => 21,
                'base_additional_cost' => 0,
                'default_restrictions' => ['experience_required', 'preparation_required'],
                'icon' => 'lightning',
                'color' => 'black',
            ],
            [
                'name' => 'Фистинг классический',
                'type' => 'bdsm',
                'description' => 'Классический фистинг',
                'sort_order' => 6,
                'is_adult_only' => true,
                'min_age' => 21,
                'base_additional_cost' => 0,
                'default_restrictions' => ['experience_required', 'preparation_required'],
                'icon' => 'lightning',
                'color' => 'black',
            ],

            // ДОПОЛНИТЕЛЬНЫЕ УСЛУГИ
            [
                'name' => 'Стриптиз',
                'type' => 'additional',
                'description' => 'Эротический танец',
                'sort_order' => 1,
                'is_adult_only' => true,
                'min_age' => 18,
                'base_additional_cost' => 0,
                'icon' => 'music',
                'color' => 'pink',
            ],

            // МАССАЖ (дополнительные к существующим)
            [
                'name' => 'Расслабляющий',
                'type' => 'massage',
                'description' => 'Расслабляющий массаж всего тела',
                'sort_order' => 1,
                'is_adult_only' => false,
                'min_age' => 16,
                'base_additional_cost' => 0,
                'icon' => 'spa',
                'color' => 'green',
            ],
            [
                'name' => 'Эротический',
                'type' => 'massage',
                'description' => 'Эротический массаж с интимными элементами',
                'sort_order' => 2,
                'is_adult_only' => true,
                'min_age' => 18,
                'base_additional_cost' => 0,
                'icon' => 'heart',
                'color' => 'red',
            ],
            [
                'name' => 'Профессиональный',
                'type' => 'massage',
                'description' => 'Профессиональный лечебный массаж',
                'sort_order' => 3,
                'is_adult_only' => false,
                'min_age' => 16,
                'base_additional_cost' => 0,
                'icon' => 'medical',
                'color' => 'blue',
            ],
        ];

        foreach ($categories as $category) {
            ExtendedServiceCategory::create($category);
        }

        $this->command->info('✅ Расширенные категории услуг созданы!');
    }
}