#!/bin/bash
echo "========================================"
echo "   УДАЛЕНИЕ LEGACY КОМПОНЕНТОВ"
echo "========================================"
echo ""
echo "Будет удалено: 18 файлов"
echo ""
read -p "Нажмите Enter для продолжения..."

rm -f "resources\js\Components\Booking\BookingForm.vue"
rm -f "resources\js\Components\Cards\Card.vue"
rm -f "resources\js\Components\Features\MasterShow\components\BookingWidget.vue"
rm -f "resources\js\Components\Features\MasterShow\components\MasterInfo.vue"
rm -f "resources\js\Components\Features\MasterShow\index.vue"
rm -f "resources\js\Components\Features\PhotoUploader\index.vue"
rm -f "resources\js\Components\Features\Services\index.vue"
rm -f "resources\js\Components\Masters\MasterDescription\index.vue"
rm -f "resources\js\Components\Masters\MasterDetails\index.vue"
rm -f "resources\js\Components\Masters\MasterHeader\index.vue"
rm -f "resources\js\Components\Media\MediaGallery\index.vue"
rm -f "resources\js\Components\Media\MediaUploader\index.vue"
rm -f "resources\js\Components\Modals\BookingModal.vue"
rm -f "resources\js\Components\UI\Forms\InputError.vue"
rm -f "resources\js\Components\UI\Forms\InputLabel.vue"
rm -f "resources\js\Components\UI\Forms\PrimaryButton.vue"
rm -f "resources\js\Components\UI\Forms\SecondaryButton.vue"
rm -f "resources\js\Components\UI\Forms\TextInput.vue"
# Удаление пустых директорий
find resources/js/Components -type d -empty -delete

echo ""
echo "========================================"
echo "   УДАЛЕНИЕ ЗАВЕРШЕНО"
echo "========================================"
