version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spa-platform:latest
    container_name: spa-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./public/uploads:/var/www/html/public/uploads
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - mysql
      - redis
    networks:
      - spa-network
    ports:
      - "8080:80"

  mysql:
    image: mysql:8.0
    container_name: spa-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - spa-network
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    container_name: spa-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data
    networks:
      - spa-network
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: spa-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - spa-network
    ports:
      - "9200:9200"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: spa-mailhog
    restart: unless-stopped
    networks:
      - spa-network
    ports:
      - "1025:1025"
      - "8025:8025"

  minio:
    image: minio/minio:latest
    container_name: spa-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - minio-data:/data
    networks:
      - spa-network
    ports:
      - "9000:9000"
      - "9001:9001"

networks:
  spa-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  elasticsearch-data:
  minio-data: